name: Simon Ostheimer
favicon: null
layout_spectrum: 0.38315903884358704
typography_spectrum: 0.2515653409063816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6672508241608739
  lightness: 0.34019976714625955
  saturation: 0.8940431911032647
  rhythmicContrast: 0.6883225224446505
purpose: []
